version: "3.8"
services:
  src-db:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./services/src-db/conf.d:/etc/mysql/conf.d:ro
      - ./services/src-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      # - ./.data/src-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=srcdb
      - MYSQL_USER=srcdb
      - MYSQL_PASSWORD=Password123!

  dest-db:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./services/dest-db/conf.d:/etc/mysql/conf.d:ro
      - ./services/dest-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      # - ./.data/dest-db:/var/lib/mysql
    depends_on: 
      - src-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=destdb
      - MYSQL_USER=destdb
      - MYSQL_PASSWORD=Password123!

  binlog-reader:
    build:
      context: ./services/binlog-reader
    restart: always
    depends_on: 
      - src-db
      - dest-db
    environment:
      - SRC_HOST=src-db
      - SRC_PORT=3306
      - SRC_USER=repl
      - SRC_PASSWORD=Password123!
      - SRC_SCHEMA=srcdb
      - DST_HOST=dest-db
      - DST_PORT=3306
      - DST_USER=destdb
      - DST_PASSWORD=Password123!
      - DST_SCHEMA=destdb

  # airflow-db:
  #   image: mysql:5.7
  #   restart: always
  #   volumes: 
  #     - ./services/airflow-db/conf.d:/etc/mysql/conf.d:ro
  #     - ./services/airflow-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  #     - ./.data/airflow-db:/var/lib/mysql
  #   environment:
  #     - MYSQL_RANDOM_ROOT_PASSWORD=yes
  #     - MYSQL_DATABASE=airflow
  #     - MYSQL_USER=airflow
  #     - MYSQL_PASSWORD=Password123!

  # airflow:
  #   image: apache/airflow:1.10.10
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   volumes: 
  #     - ./services/airflow/entrypoint.sh:/opt/airflow/entrypoint.sh:ro
  #     - ./services/airflow/dags:/opt/airflow/dags
  #   entrypoint: /opt/airflow/entrypoint.sh
  #   depends_on: 
  #     - airflow-db
  #   environment: 
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://airflow:Password123!@airflow-db:3306/airflow
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    
    